Repository internxt/payments-server, pull requests merged in 2024-11, with the labels that each got.

#118 [_]: fix/avoid getting the customerId so many times
  src/webhooks/handleInvoiceCompleted.ts
Labels: bug, ready-for-preview

#119 [_]: fix/avoid canceling business sub, avoid updating the lifetime field when it is not needed and return the correct sub for each user type
  src/controller.ts
  src/webhooks/handleInvoiceCompleted.ts
Labels: bug, ready-for-preview

#120 [PB-3315]: feat/update seats in business sub
  src/app.ts
  src/controller-migration.ts
  src/controller/business.controller.ts
  src/controller/payments.controller.ts
  src/core/users/User.ts
  src/server.ts
  src/services/cache.service.ts
  src/services/licenseCodes.service.ts
  src/services/objectStorage.service.ts
  src/services/payment.service.ts
  src/services/storage.service.ts
  src/services/users.service.ts
  src/utils/assertUser.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/handleInvoicePaymentFailed.ts
  src/webhooks/handleLifetimeRefunded.ts
  src/webhooks/handlePaymentIntentSucceeded.ts
  src/webhooks/handlePaymentMethodAttached.ts
  src/webhooks/handleSetupIntentSucceded.ts
  src/webhooks/handleSubscriptionCanceled.ts
  src/webhooks/handleSubscriptionUpdated.ts
  src/webhooks/index.ts
Labels: enhancement, ready-for-preview

#125 [_]: chore/node 18 and updating dependencies
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-and-publish-preview.yaml
  .github/workflows/deploy-pr-preview.yaml
  .github/workflows/slash-command-dispatcher.yaml
  infrastructure/development.Dockerfile
  infrastructure/preview.Dockerfile
  package.json
  src/app.ts
  src/controller-migration.ts
  src/controller/business.controller.ts
  src/controller/payments.controller.ts
  src/server.ts
  yarn.lock
Labels: enhancement, ready-for-preview, maintenance

#126 [_]: feat/upgrade-to-Node-20
  Dockerfile
  infrastructure/development.Dockerfile
  infrastructure/preview.Dockerfile
  package.json
  src/app.ts
  src/webhooks/handleInvoiceCompleted.ts
  tsconfig.json
Labels: enhancement, ready-for-preview, maintenance

#124 [PB-3313]: feat/send the seats for business subscription
  src/controller/business.controller.ts
  src/services/payment.service.ts
  src/services/users.service.ts
  src/webhooks/handleInvoiceCompleted.ts
Labels: enhancement, ready-for-preview

#128 [_]: fix/send the workspaceID to check if workspace can be updated
  src/controller/business.controller.ts
  src/services/users.service.ts
Labels: enhancement, ready-for-preview

#129 [_]: feat/Sonarcloud analysis
  .github/workflows/sonarcloud-analysis.yml
  sonar-project.properties
Labels: enhancement, ready-for-preview

#130 [_]: feat/pr-size-control [skip ci]
  .github/workflows/pr-size-control.yml
Labels: enhancement, ready-for-preview

#132 [_]: feat/modify CI/CD pipeline configurations to use node 20
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-and-publish-preview.yaml
  .github/workflows/deploy-pr-preview.yaml
  .github/workflows/slash-command-dispatcher.yaml
Labels: enhancement, ready-for-preview, maintenance

#135 [_]: feat/users tests coverage
  .github/workflows/sonarcloud-analysis.yml
  package.json
  sonar-project.properties
  src/config.ts
  src/services/payment.service.ts
  tests/src/mocks/index.ts
  tests/src/services/UsersService.test.ts
  tests/src/services/users.service.test.ts
Labels: enhancement, ready-for-preview, maintenance

#137 [_]: tests/payment controller coverage
  package.json
  src/server.ts
  src/services/payment.service.ts
  tests/src/controller.test.ts
  tests/src/mocks/index.ts
  tests/src/payments.controller.test.ts
  tests/src/utils/factory.ts
  tests/src/utils/preloadMongoDBData.ts
  yarn.lock
Labels: enhancement, ready-for-preview, maintenance

#136 [_]: feat/payments service test
  package.json
  src/server.ts
  src/services/payment.service.ts
  tests/src/controller.test.ts
  tests/src/mocks/index.ts
  tests/src/payments.controller.test.ts
  tests/src/services/PaymentService.test.ts
  tests/src/services/payment.service.test.ts
  tests/src/services/users.service.test.ts
  tests/src/utils/factory.ts
  tests/src/utils/preloadMongoDBData.ts
  yarn.lock
Labels: enhancement, ready-for-preview, maintenance

#138 [_]: doc/update-readme
  README.md
Labels: documentation, ready-for-preview
