Repository internxt/payments-server, pull requests merged in 2024-12, with the labels that each got.

#133 [_]: feat/list-accepted-crypto-currencies
  .env.template
  .github/workflows/sonarcloud-analysis.yml
  src/config.ts
  src/controller/payments.controller.ts
  src/server.ts
  src/services/bit2me.service.ts
  src/services/payment.service.ts
  src/webhooks/providers/bit2me/doc.md
  tests/src/services/bit2me.service.test.ts
  tests/src/services/payment.service.test.ts
  tests/src/services/users.service.test.ts
Labels: enhancement, ready-for-preview

#141 [PB-3407]: fix/wrong plan display when partial refund is made for lifetime plans
  .github/workflows/sonarcloud-analysis.yml
  src/webhooks/index.ts
Labels: bug, ready-for-preview

#142 [_]: feat/handle lost disputes through the webhook
  package.json
  src/webhooks/handleDisputeResult.ts
  src/webhooks/handleSetupIntentSucceded.ts
  src/webhooks/handleSubscriptionCanceled.ts
  src/webhooks/handleSubscriptionUpdated.ts
  src/webhooks/index.ts
  tests/src/mocks/index.ts
  tests/src/services/payment.service.test.ts
  tests/src/services/users.service.test.ts
  tests/src/webhooks/handleDisputeResult.test.ts
  yarn.lock
Labels: enhancement, ready-for-preview

#143 [_]: chore/upgrade to node v22
  .github/workflows/build-and-deploy.yml
  .github/workflows/build-and-publish-preview.yaml
  .github/workflows/deploy-pr-preview.yaml
  .github/workflows/slash-command-dispatcher.yaml
  .github/workflows/sonarcloud-analysis.yml
  Dockerfile
  README.md
  infrastructure/development.Dockerfile
  infrastructure/preview.Dockerfile
  package.json
  yarn.lock
Labels: enhancement, ready-for-preview, maintenance, dependencies

#147 [_]: feat/tiers-per-product
  src/core/users/MongoDBTiersRepository.ts
  src/services/tiers.service.ts
  tests/src/mocks/index.ts
  tests/src/services/tiers.service.test.ts
  tests/src/utils/factory.ts
Labels: enhancement, ready-for-preview
