Repository internxt/payments-server, pull requests merged in 2024-04, with the labels that each got.

#55 chore: added temporal endpoint for plans migration
  src/app.ts
  src/controller-migration.ts
  src/core/users/User.ts
  src/services/PaymentService.ts
Labels: enhancement, ready-for-preview

#52 [PB-1435]: feat/update users tier on subscription change.
  src/constants.ts
  src/services/StorageService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handleLifetimeRefunded.ts
  src/webhooks/handleSubscriptionCanceled.ts
  src/webhooks/handleSubscriptionUpdated.ts
  src/webhooks/index.ts
Labels: enhancement, preview, deployed, ready-for-preview

#56 [_]: feat/display-billing-remotely
  src/controller.ts
  src/core/users/MongoDBDisplayBillingRepository.ts
  src/server.ts
  src/services/UsersService.ts
Labels: enhancement

#58 [_]: feat/add-coupons-tracking-system
  src/cli/load-license-codes.ts
  src/controller.ts
  src/core/coupons/Coupon.ts
  src/core/coupons/CouponsRepository.ts
  src/core/coupons/MongoDBCouponsRepository.ts
  src/core/coupons/MongoDBUsersCouponsRepository.ts
  src/core/coupons/UserCoupon.ts
  src/core/coupons/UsersCouponsRepository.ts
  src/core/users/MongoDBUsersRepository.ts
  src/core/users/User.ts
  src/core/users/UsersRepository.ts
  src/server.ts
  src/services/UsersService.ts
Labels: enhancement, ready-for-preview

#59 [_]: feat/add method in webhook
  src/controller.ts
  src/core/coupons/MongoDBUsersCouponsRepository.ts
  src/services/PaymentService.ts
  src/services/UsersService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handleSubscriptionUpdated.ts
  src/webhooks/index.ts
Labels: enhancement, ready-for-preview
