Repository internxt/payments-server, pull requests merged in 2024-07, with the labels that each got.

#70 Chore: update b2b methods
  src/controller.ts
  src/core/users/User.ts
  src/services/CacheService.ts
  src/services/PaymentService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handleSubscriptionCanceled.ts
Labels: enhancement, ready-for-preview

#68 [PB-2115] feat: b2b update subscription payment method
  src/controller.ts
  src/core/users/User.ts
  src/services/PaymentService.ts
  src/services/UsersService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handleSetupIntentSucceded.ts
  src/webhooks/handleSubscriptionUpdated.ts
  src/webhooks/index.ts
Labels: enhancement, ready-for-preview

#72 fix: make quantity adjustable on stripe checkout
  src/services/PaymentService.ts
Labels: ready-for-preview

#73 [_]: feat/workspaces-product-integration
  src/controller.ts
  src/core/users/User.ts
  src/services/CacheService.ts
  src/services/PaymentService.ts
  src/services/UsersService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handleSetupIntentSucceded.ts
  src/webhooks/handleSubscriptionCanceled.ts
  src/webhooks/handleSubscriptionUpdated.ts
  src/webhooks/index.ts
Labels: preview, deployed, ready-for-preview

#78 fix: send number of seats to gateway that creates new workspaces
  src/services/UsersService.ts
  src/webhooks/handleSubscriptionUpdated.ts
Labels: ready-for-preview

#79 fix: edit billing details
  src/controller.ts
  src/services/PaymentService.ts
  src/services/UsersService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
Labels: ready-for-preview

#80 [_]: fix/allow-product-currency-parametrization-on-checkout
  src/services/PaymentService.ts
Labels: bug, ready-for-preview

#81 [MKT-408]: feat/use promotion code ID instead of coupon ID
  src/controller.ts
  src/services/PaymentService.ts
Labels: enhancement, ready-for-preview
