Repository internxt/payments-server, pull requests merged in 2024-08, with the labels that each got.

#65 [MKT-305]: feat/handle checkout manually
  jest.config.js
  package.json
  src/app.ts
  src/cli/load-license-codes.ts
  src/controller.ts
  src/server.ts
  src/services/PaymentService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handlePaymentIntentCompleted.ts
  src/webhooks/handleSubscriptionCanceled.ts
  src/webhooks/index.ts
  tests/src/controller.test.ts
  tests/src/mocks/index.ts
  tests/src/services/PaymentService.test.ts
  tests/src/services/UsersService.test.ts
  tests/src/utils/factory.ts
  tests/tsconfig.json
  yarn.lock
Labels: enhancement, ready-for-preview

#83 [_]: fix/handle payment intent completed
  src/controller.ts
  src/services/PaymentService.ts
  src/webhooks/handleCheckoutSessionCompleted.ts
  src/webhooks/handlePaymentIntentCompleted.ts
Labels: bug, ready-for-preview

#85 [_]: fix/change webhook event
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/index.ts
Labels: bug, ready-for-preview

#86 [MKT-413]: fix/coupon codes
  src/controller.ts
  src/services/PaymentService.ts
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/handleSubscriptionUpdated.ts
  src/webhooks/index.ts
Labels: enhancement, ready-for-preview

#88 [_]: fix/deployment
  src/cli/load-license-codes.ts
Labels: bug, ready-for-preview

#89 [_]: fix/endpoint for promotion codes
  src/controller.ts
  src/services/PaymentService.ts
Labels: bug, ready-for-preview

#90 [_]: fix: store coupon used by user in handleInvoiceCheckout
  src/services/PaymentService.ts
  src/webhooks/handleInvoiceCompleted.ts
Labels: bug, ready-for-preview

#87 [_]: feat/subscribe-customer-after-object-storage-verification-charge
  .env.template
  src/config.ts
  src/controller.ts
  src/services/PaymentService.ts
  src/webhooks/handleInvoiceCompleted.ts
Labels: ready-for-preview

#91 [_]: feat/create-object-storage-account-on-invoice-completed
  .env.template
  src/app.ts
  src/config.ts
  src/server.ts
  src/services/ObjectStorageService.ts
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/index.ts
  tsconfig.json
Labels: enhancement, ready-for-preview

#92 [_]: fix/exclude-business-products-from-invoice-payment-succeeded
  src/services/PaymentService.ts
  src/webhooks/handleInvoiceCompleted.ts
Labels: bug, ready-for-preview

#93 [_]: fix/allow-customer-creation-when-missing-on-payment-succeeded
  src/webhooks/handleInvoiceCompleted.ts
Labels: bug, ready-for-preview

#94 [_]: fix/check if there is a subscription before creating one
  src/controller.ts
  src/services/PaymentService.ts
Labels: bug, enhancement, ready-for-preview

#95 [_]: fix/check the subscription type before creating sub
  src/services/PaymentService.ts
Labels: bug, ready-for-preview

#97 [_]: fix/remove the sub check before creating the subscription
  src/services/PaymentService.ts
Labels: bug

#99 [_] : bugfix/Fix impact in integrated checkout
  src/services/PaymentService.ts
Labels: bug, ready-for-preview

#100 [_]: Return subscription id always when create a subscription
  src/services/PaymentService.ts
Labels: enhancement, ready-for-preview

#101 [_]: feat/basic-object-storage-account-lifecycle-management
  src/services/ObjectStorageService.ts
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/handleInvoicePaymentFailed.ts
  src/webhooks/index.ts
Labels: enhancement

#96 [_]: feat/endpoint to create sub for obj storage
  src/controller.ts
Labels: enhancement, ready-for-preview

#104 [MKT-424]: fix/updating subscriptions and promo codes
  src/controller.ts
  src/services/PaymentService.ts
Labels: bug, enhancement, ready-for-preview

#105 [_]: fix/check if customer exists before creating one
  src/controller.ts
  src/services/PaymentService.ts
Labels: bug, enhancement, ready-for-preview

#108 [_]: fix/return the existing customer and not an Error
  src/services/PaymentService.ts
Labels: bug

#107 [MKT-417]: feat/optional params for companies
  src/controller.ts
  src/services/PaymentService.ts
Labels: enhancement, ready-for-preview

#109 [_]: feat/attaching the company tax ID to the customer data
  src/controller.ts
  src/services/PaymentService.ts
  src/webhooks/handleSubscriptionUpdated.ts
Labels: enhancement, ready-for-preview

#110 [_]: fix/send error messages when creating subscription endpoint fails
  src/controller.ts
  src/services/PaymentService.ts
Labels: enhancement, ready-for-preview
