Repository internxt/payments-server, pull requests merged in 2025-02, with the labels that each got.

#152 [_]: feat/Belgium Vat ID
  src/services/payment.service.ts
Labels: enhancement, ready-for-preview

#157 [_]: tests/new-test-fixtures
  package.json
  tests/src/fixtures.spec.ts
  tests/src/fixtures.ts
Labels: enhancement, ready-for-preview

#158 [_]: tests/more-test-fixtures
  tests/src/fixtures.spec.ts
  tests/src/fixtures.ts
Labels: enhancement, ready-for-preview

#162 [_]: feat/improving-fixtures
  tests/src/fixtures.spec.ts
  tests/src/fixtures.ts
Labels: enhancement, ready-for-preview

#163 [_]: tests/fixtures in user service test
  tests/src/services/users.service.test.ts
Labels: enhancement, ready-for-preview

#161 [_]: ci/workflow-to-run-tests-on-PRs
  .github/workflows/tests.yaml
Labels: enhancement, ready-for-preview

#159 [_]: refactor/use-dynamic-fixtures-in-tests
  tests/src/payments.controller.test.ts
  tests/src/services/bit2me.service.test.ts
  tests/src/services/payment.service.test.ts
  tests/src/services/tiers.service.test.ts
  tests/src/services/users.service.test.ts
  tests/src/utils/preloadMongoDBData.ts
  tests/src/webhooks/handleDisputeResult.test.ts
Labels: enhancement, ready-for-preview, maintenance

#160 [_]: test/remove useless mocks
  tests/src/mocks/index.ts
Labels: enhancement, ready-for-preview

#167 [_]: feat/get-user-products-by-user-Id-and-tier-id
  src/core/users/MongoDBTiersRepository.ts
  src/services/tiers.service.ts
  tests/src/core/users/MongoDBTiersRepository.test.ts
  tests/src/services/tiers.service.test.ts
  tests/src/utils/factory.ts
Labels: enhancement

#166 [PB-3884]: feat/store-users-tiers-relationship
  src/core/users/MongoDBTiersRepository.ts
  src/core/users/MongoDBUsersTiersRepository.ts
  src/core/users/Tier.ts
  src/services/tiers.service.ts
  tests/src/core/users/MongoDBTiersRepository.test.ts
  tests/src/core/users/MongoDBUsersTiersRepository.test.ts
  tests/src/fixtures.spec.ts
  tests/src/fixtures.ts
  tests/src/payments.controller.test.ts
  tests/src/services/tiers.service.test.ts
Labels: enhancement, ready-for-preview

#168 [_]: feat/handling user-tier relationship
  src/core/users/MongoDBTiersRepository.ts
  src/core/users/MongoDBUsersTiersRepository.ts
  src/server.ts
  src/services/tiers.service.ts
  tests/src/core/users/MongoDBTiersRepository.test.ts
  tests/src/services/tiers.service.test.ts
  tests/src/utils/factory.ts
Labels: enhancement, ready-for-preview

#153 [PB-3813]: feat/apply-vpn-features
  .env.template
  .github/workflows/sonarcloud-analysis.yml
  .github/workflows/tests.yaml
  src/config.ts
  src/services/tiers.service.ts
  src/services/users.service.ts
  tests/src/services/tiers.service.test.ts
  tests/src/services/users.service.test.ts
Labels: enhancement, ready-for-preview

#171 [_]: feat/subscriptions-with-trial-agreements
  .env.template
  .github/workflows/sonarcloud-analysis.yml
  .github/workflows/tests.yaml
  src/config.ts
  src/controller/payments.controller.ts
  src/services/payment.service.ts
  tests/src/services/payment.service.test.ts
Labels: enhancement, ready-for-preview

#169 [PB-3913/PB-3914]: feat/handle users tiers relationship
  src/services/payment.service.ts
  src/services/tiers.service.ts
  src/webhooks/utils/handleUserFeatures.ts
  tests/src/fixtures.ts
  tests/src/services/payment.service.test.ts
  tests/src/services/tiers.service.test.ts
  tests/src/services/users.service.test.ts
  tests/src/webhooks/utils/handleUserFeatures.test.ts
Labels: enhancement, ready-for-preview

#170 [PB-3915]: feat/remove tier for canceled subs and refunded lifetimes
  src/server.ts
  src/services/tiers.service.ts
  src/services/users.service.ts
  src/webhooks/utils/handleCancelPlan.ts
  tests/src/services/tiers.service.test.ts
  tests/src/services/users.service.test.ts
  tests/src/webhooks/utils/handleCancelPlan.test.ts
  tests/src/webhooks/utils/handleUserFeatures.test.ts
Labels: enhancement, ready-for-preview

#172 [_]: feat/extract payment succeed user flow
  src/services/tiers.service.ts
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/utils/handleOldInvoiceCompletedFlow.ts
  tests/src/fixtures.ts
  tests/src/services/tiers.service.test.ts
  tests/src/webhooks/utils/handleOldInvoiceCompletedFlow.test.ts
Labels: enhancement, ready-for-preview

#174 [_]: tests/handle invoice completed
  src/webhooks/handleInvoiceCompleted.ts
  tests/src/webhooks/handleInvoiceCompleted.test.ts
Labels: enhancement, ready-for-preview

#173 [_]: feat/implement user drive updates
  src/webhooks/handleInvoiceCompleted.ts
  tests/src/fixtures.ts
  tests/src/webhooks/handleInvoiceCompleted.test.ts
Labels: enhancement, ready-for-preview

#175 [PB-3887/PB-3913/PB-3914]: feat/handle new tier products after successful payment
  src/app.ts
  src/core/users/MongoDBTiersRepository.ts
  src/services/tiers.service.ts
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/index.ts
  src/webhooks/utils/handleUserFeatures.ts
  tests/src/core/users/MongoDBTiersRepository.test.ts
  tests/src/services/tiers.service.test.ts
  tests/src/webhooks/handleInvoiceCompleted.test.ts
  tests/src/webhooks/utils/handleUserFeatures.test.ts
Labels: enhancement, ready-for-preview

#176 [PB-3915]: feat/delete user tier in cancel sub webhook event
  src/webhooks/handleDisputeResult.ts
  src/webhooks/handleLifetimeRefunded.ts
  src/webhooks/index.ts
  tests/src/fixtures.ts
  tests/src/webhooks/handleDisputeResult.test.ts
  tests/src/webhooks/handleLifetimeRefunded.test.ts
Labels: enhancement, ready-for-preview

#177 [PB-3915]: feat/handle subscription canceled
  src/webhooks/handleSubscriptionCanceled.ts
  src/webhooks/index.ts
  src/webhooks/utils/handleOldInvoiceCompletedFlow.ts
  tests/src/webhooks/handleSubscriptionCanceled.test.ts
Labels: enhancement, ready-for-preview

#178 [_]: feat/show-plans-with-not-show
  src/services/payment.service.ts
Labels: enhancement, ready-for-preview

#179 [_]: feat/generate-trial-token
  src/controller/payments.controller.ts
Labels: ready-for-preview
