Repository internxt/payments-server, pull requests merged in 2025-05, with the labels that each got.

#203 [PB-4338]: fix(customer-creation)/customer creation
  src/services/customerSync.service.ts
Labels: bug, ready-for-preview

#201 [_]: fix/include customer email in error logging for customer creation
  src/controller/payments.controller.ts
  src/services/payment.service.ts
  tests/src/controller/payments.controller.test.ts
Labels: ready-for-preview

#204 [_]: feat/handling errors globally
  sonar-project.properties
  src/app.ts
  src/errors/Errors.ts
  src/errors/HttpError.ts
  src/plugins/error-handler.ts
  tests/src/controller/payments.controller.test.ts
  tests/src/plugins/error-handler.test.ts
  tests/src/utils/error-test-routes.ts
Labels: enhancement, ready-for-preview

#207 [_]: fix/users-coupon relationship for subscriptions
  src/webhooks/handleInvoiceCompleted.ts
  src/webhooks/handleSubscriptionCanceled.ts
  tests/src/webhooks/handleInvoiceCompleted.test.ts
Labels: bug, ready-for-preview

#208 [_]: feat/create subscription
  src/controller/checkout.controller.ts
  src/errors/Errors.ts
  src/services/payment.service.ts
  tests/src/controller/checkout.controller.test.ts
  tests/src/controller/payments.controller.test.ts
  tests/src/fixtures.ts
  tests/src/services/payment.service.test.ts
Labels: enhancement, ready-for-preview

#209 [_]: feat/create payment intent
  src/controller/checkout.controller.ts
  src/services/payment.service.ts
  tests/src/controller/checkout.controller.test.ts
  tests/src/fixtures.ts
  tests/src/services/payment.service.test.ts
Labels: enhancement, ready-for-preview

#210 [_]: feat/get price by id
  fastify.d.ts
  src/controller/checkout.controller.ts
  src/services/payment.service.ts
  tests/src/controller/checkout.controller.test.ts
  tests/src/fixtures.ts
  tests/src/services/payment.service.test.ts
Labels: enhancement, ready-for-preview

#211 [_]: fix/user address
  src/controller/checkout.controller.ts
  src/services/payments/checkout.service.ts
Labels: bug

#212 [_]: feat/add logs
  src/controller/checkout.controller.ts
Labels: enhancement

#213 [_]: feat/enable automatic tax for subscriptions and invoices
  src/controller/checkout.controller.ts
  src/services/payment.service.ts
  tests/src/services/payment.service.test.ts
Labels: enhancement, ready-for-preview

#214 [_]: feat/calculate taxes using discounts
  fastify.d.ts
  src/controller/checkout.controller.ts
  src/services/payment.service.ts
  tests/src/controller/checkout.controller.test.ts
  tests/src/controller/payments.controller.test.ts
  tests/src/fixtures.spec.ts
  tests/src/fixtures.ts
  tests/src/services/payment.service.test.ts
Labels: enhancement, ready-for-preview

#215 [_]: fix/price in checkout
  src/controller/checkout.controller.ts
  tests/src/controller/checkout.controller.test.ts
Labels: enhancement, ready-for-preview

#216 [_]: feat/create customer with postal code and country
  src/controller/checkout.controller.ts
  tests/src/controller/checkout.controller.test.ts
Labels: enhancement, ready-for-preview

#217 [_]: feat/use company name if provided to create customer
  src/controller/checkout.controller.ts
  src/services/payments/checkout.service.ts
Labels: enhancement, ready-for-preview

#219 [_]: fix/throw the error back to the parent
  src/services/tiers.service.ts
Labels: bug

#220 [_]: feat/add customer name when creating it
  src/controller/checkout.controller.ts
Labels: enhancement, ready-for-preview

#221 [_]: hotfix/return when applying obj storage
  src/webhooks/handleInvoiceCompleted.ts
Labels: bug

#222 [_]: feat/allow fetch price without taxes
  src/controller/checkout.controller.ts
  src/services/payment.service.ts
  tests/src/controller/checkout.controller.test.ts
Labels: enhancement, ready-for-preview

#223 [_]: fix/get the allowed product Id for lifetime plans
  src/services/tiers.service.ts
Labels: bug, ready-for-preview

#224 [_]: fix/customer name query param when creating customer
  src/controller/checkout.controller.ts
  tests/src/controller/checkout.controller.test.ts
Labels: enhancement, ready-for-preview

#225 [_]: feat/eu_vat to check Tax IDs of European countries
  src/services/payment.service.ts
  tests/src/controller/checkout.controller.test.ts
  tests/src/fixtures.spec.ts
  tests/src/fixtures.ts
Labels: enhancement, ready-for-preview

#226 [PB-4388]: feat/activate automatic tax when creating sub
  src/controller/payments.controller.ts
  src/services/payment.service.ts
  tests/src/controller/checkout.controller.test.ts
  tests/src/controller/payments.controller.test.ts
  tests/src/fixtures.ts
Labels: enhancement, ready-for-preview

#228 [_]: fixpayment failed for object storage subscriptions
  src/webhooks/handleInvoicePaymentFailed.ts
Labels: bug, ready-for-preview

#230 [_]: tests/use query object to pass the query parameters
  tests/src/controller/checkout.controller.test.ts
Labels: bug, ready-for-preview
