Repository internxt/payments-server, pull requests merged in 2025-10, with the labels that each got.

#308 [PB-5033]: feat/notify-failed-payment-on-invoice-payment-failed
  src/services/users.service.ts
  src/webhooks/handleInvoicePaymentFailed.ts
  src/webhooks/index.ts
  tests/src/webhooks/handleInvoicePaymentFailed.test.ts
  tests/src/webhooks/webhook.test.ts
Labels: ready-for-preview

#309 [PB-4944]: feat/pass drive tier id when updating drive storage
  src/app.ts
  src/controller/business.controller.ts
  src/core/users/Tier.ts
  src/services/licenseCodes.service.ts
  src/services/storage.service.ts
  src/services/tiers.service.ts
  src/services/users.service.ts
  src/webhooks/events/invoices/InvoiceCompletedHandler.ts
  src/webhooks/handleLifetimeRefunded.ts
  src/webhooks/handleSubscriptionCanceled.ts
  tests/src/controller/business.controller.test.ts
  tests/src/fixtures.ts
  tests/src/services/licenseCodes.service.test.ts
  tests/src/services/products.service.test.ts
  tests/src/services/storage.service.test.ts
  tests/src/services/tiers.service.test.ts
  tests/src/services/users.service.test.ts
  tests/src/webhooks/events/invoices/InvoiceCompletedHandler.test.ts
  tests/src/webhooks/handleLifetimeRefunded.test.ts
  tests/src/webhooks/handleSubscriptionCanceled.test.ts
Labels: enhancement, ready-for-preview

#311 [_]: fix/fetch the price by id directly from Stripe
  src/services/licenseCodes.service.ts
  src/services/payment.service.ts
  tests/src/services/licenseCodes.service.test.ts
Labels: bug, ready-for-preview
